apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  selector:
    matchLabels:
      app: node-app
  replicas: 2
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: palopalepalo/noteapp:latest
          ports:
            - containerPort: 4000
        env:
        - name : MONGODB_HOST
          value : "host"
        - name : MONGODB_DB
          value: "notesdb"
        - name : PORT
          value: "4000"